INSERT INTO datagrid.personnel (
        name,
        email,
        department,
        gender,
        role,
        salary,
        bonus,
        rating,
        tenure,
        is_valid,
        is_active,
        data
    )
VALUES (
        'Papp Orsolya',
        'orsolya.papp@example.com',
        'MGT',
        'Female',
        'PM',
        97432,
        17388,
        1,
        12,
        true,
        true,
        '{"experience": 3, "certifications": ["SCRUM", "CKA"]}'
    ),
    (
        'Balog Timea',
        'timea.balog@example.com',
        'OPS',
        'Female',
        'OPS_MGR',
        106529,
        10559,
        1,
        7,
        true,
        true,
        '{"experience": 12}'
    ),
    (
        'Varga Kata',
        'kata.varga@example.com',
        'MGT',
        'Female',
        'PM',
        112410,
        15910,
        4,
        8,
        true,
        true,
        '{"experience": 8}'
    ),
    (
        'Molnar Orsolya',
        'orsolya.molnar@example.com',
        'SALES',
        'Female',
        'SALES_REP',
        88719,
        13265,
        3,
        6,
        false,
        true,
        '{"experience": 8}'
    ),
    (
        'Hegedus David',
        'david.hegedus@example.com',
        'HR',
        'Male',
        'HR_SPEC',
        136453,
        9398,
        2,
        10,
        true,
        true,
        '{"experience": 14}'
    ),
    (
        'Nemeth Attila',
        'attila.nemeth@example.com',
        'FIN',
        'Male',
        'FIN_ANL',
        100947,
        15902,
        1,
        7,
        true,
        true,
        '{"experience": 1}'
    ),
    (
        'Takacs David',
        'david.takacs@example.com',
        'MGT',
        'Male',
        'PM',
        58619,
        9931,
        5,
        12,
        true,
        true,
        '{"experience": 6, "certifications": ["CISSP"]}'
    ),
    (
        'Simon Cecil',
        'cecil.simon@example.com',
        'HR',
        'Male',
        'HR_SPEC',
        97827,
        10959,
        1,
        10,
        true,
        true,
        '{"experience": 1}'
    ),
    (
        'Molnar Sara',
        'sara.molnar@example.com',
        'FIN',
        'Female',
        'FIN_ANL',
        100045,
        9700,
        5,
        12,
        true,
        false,
        '{"experience": 1}'
    ),
    (
        'Nemeth Kata',
        'kata.nemeth@example.com',
        'ENG',
        'Female',
        'SWE',
        143610,
        16860,
        3,
        13,
        true,
        true,
        '{"experience": 1, "tags": ["react"]}'
    ),
    (
        'Balog Zoltan',
        'zoltan.balog@example.com',
        'SALES',
        'SALES_REP',
        97424,
        4397,
        4,
        11,
        true,
        true,
        '{"experience": 3}'
    ),
    (
        'Hegedus Luca',
        'luca.hegedus@example.com',
        'FIN',
        'FIN_ANL',
        67417,
        18062,
        4,
        5,
        true,
        true,
        '{"experience": 10}'
    ),
    (
        'Balog Istvan',
        'istvan.balog@example.com',
        'HR',
        'HR_SPEC',
        122630,
        8924,
        5,
        4,
        true,
        false,
        '{"experience": 4}'
    ),
    (
        'Kiss Elemer',
        'elemer.kiss@example.com',
        'OPS',
        'OPS_MGR',
        122116,
        11760,
        3,
        13,
        true,
        true,
        '{"experience": 14}'
    ),
    (
        'Lakatos Jozsef',
        'jozsef.lakatos@example.com',
        'SALES',
        'SALES_REP',
        84838,
        14115,
        2,
        5,
        true,
        false,
        '{"experience": 20}'
    ),
    (
        'Molnar Peter',
        'peter.molnar@example.com',
        'DSG',
        'DSG_UI',
        51990,
        17098,
        1,
        9,
        true,
        false,
        '{"experience": 7}'
    ),
    (
        'Varga Ferenc',
        'ferenc.varga@example.com',
        'SALES',
        'SALES_REP',
        58984,
        14047,
        1,
        10,
        true,
        false,
        '{"experience": 14}'
    ),
    (
        'Varga Orsolya',
        'orsolya.varga@example.com',
        'MGT',
        'PM',
        47512,
        9066,
        3,
        14,
        true,
        true,
        '{"experience": 13, "certifications": ["AWS", "CKA"]}'
    ),
    (
        'Molnar David',
        'david.molnar@example.com',
        'FIN',
        'FIN_ANL',
        51049,
        14514,
        2,
        9,
        true,
        true,
        '{"experience": 3}'
    ),
    (
        'Lakatos Hugo',
        'hugo.lakatos@example.com',
        'HR',
        'HR_SPEC',
        68915,
        8270,
        5,
        4,
        true,
        true,
        '{"experience": 18}'
    ),
    (
        'Szabo Ferenc',
        'ferenc.szabo@example.com',
        'DSG',
        'DSG_UI',
        120191,
        7991,
        1,
        10,
        true,
        true,
        '{"experience": 3}'
    ),
    (
        'Simon David',
        'david.simon@example.com',
        'MGT',
        'PM',
        103086,
        6201,
        4,
        1,
        true,
        true,
        '{"experience": 18, "certifications": ["SCRUM", "PMP"]}'
    ),
    (
        'Papp Peter',
        'peter.papp@example.com',
        'ENG',
        'SWE',
        47366,
        17741,
        5,
        1,
        true,
        true,
        '{"experience": 7, "tags": ["go"]}'
    ),
    (
        'Farkas Elemer',
        'elemer.farkas@example.com',
        'SALES',
        'SALES_REP',
        65780,
        15503,
        5,
        9,
        true,
        true,
        '{"experience": 19}'
    ),
    (
        'Szabo Gyorgy',
        'gyorgy.szabo@example.com',
        'FIN',
        'FIN_ANL',
        67525,
        13474,
        4,
        14,
        true,
        true,
        '{"experience": 12}'
    ),
    (
        'Varga Tamas',
        'tamas.varga@example.com',
        'SALES',
        'SALES_REP',
        73587,
        12315,
        1,
        9,
        true,
        true,
        '{"experience": 16}'
    ),
    (
        'Balog Sara',
        'sara.balog@example.com',
        'DSG',
        'DSG_UI',
        122655,
        1964,
        1,
        10,
        true,
        true,
        '{"experience": 16}'
    ),
    (
        'Kelemen Orsolya',
        'orsolya.kelemen@example.com',
        'MGT',
        'PM',
        63655,
        10155,
        4,
        8,
        true,
        true,
        '{"experience": 19}'
    ),
    (
        'Farkas Adam',
        'adam.farkas@example.com',
        'SALES',
        'SALES_REP',
        108671,
        9953,
        4,
        11,
        true,
        true,
        '{"experience": 20}'
    ),
    (
        'Farkas Elemer',
        'elemer.farkas@example.com',
        'FIN',
        'FIN_ANL',
        109103,
        19238,
        1,
        13,
        true,
        true,
        '{"experience": 1}'
    ),
    (
        'Lakatos Attila',
        'attila.lakatos@example.com',
        'DSG',
        'DSG_UI',
        124857,
        2909,
        5,
        3,
        true,
        true,
        '{"experience": 14}'
    ),
    (
        'Toth Andras',
        'andras.toth@example.com',
        'FIN',
        'FIN_ANL',
        56740,
        11346,
        3,
        12,
        true,
        true,
        '{"experience": 10}'
    ),
    (
        'Papp Timea',
        'timea.papp@example.com',
        'SALES',
        'SALES_REP',
        47082,
        12408,
        3,
        5,
        true,
        true,
        '{"experience": 11}'
    ),
    (
        'Toth Gabor',
        'gabor.toth@example.com',
        'HR',
        'HR_SPEC',
        46505,
        4506,
        2,
        4,
        true,
        true,
        '{"experience": 8}'
    ),
    (
        'Hegedus Laszlo',
        'laszlo.hegedus@example.com',
        'ENG',
        'SWE',
        55333,
        17130,
        5,
        13,
        true,
        true,
        '{"experience": 3, "tags": ["java", "kubernetes", "js"]}'
    ),
    (
        'Simon Laszlo',
        'laszlo.simon@example.com',
        'SALES',
        'SALES_REP',
        90791,
        13927,
        5,
        11,
        false,
        true,
        '{"experience": 19}'
    ),
    (
        'Papp Adam',
        'adam.papp@example.com',
        'FIN',
        'FIN_ANL',
        106100,
        1192,
        1,
        10,
        true,
        true,
        '{"experience": 11}'
    ),
    (
        'Szabo Laszlo',
        'laszlo.szabo@example.com',
        'FIN',
        'FIN_ANL',
        85192,
        9327,
        4,
        15,
        false,
        true,
        '{"experience": 10}'
    ),
    (
        'Balog Tamas',
        'tamas.balog@example.com',
        'OPS',
        'OPS_MGR',
        125890,
        3689,
        1,
        1,
        true,
        true,
        '{"experience": 20}'
    ),
    (
        'Nemeth Peter',
        'peter.nemeth@example.com',
        'DSG',
        'DSG_UI',
        47748,
        2209,
        4,
        3,
        true,
        true,
        '{"experience": 5}'
    ),
    (
        'Szabo Mari',
        'mari.szabo@example.com',
        'DSG',
        'DSG_UI',
        131995,
        10067,
        3,
        3,
        true,
        true,
        '{"experience": 1}'
    ),
    (
        'Molnar Bela',
        'bela.molnar@example.com',
        'OPS',
        'OPS_MGR',
        128806,
        19978,
        1,
        15,
        true,
        true,
        '{"experience": 11}'
    ),
    (
        'Juhasz Andras',
        'andras.juhasz@example.com',
        'OPS',
        'OPS_MGR',
        139573,
        14339,
        4,
        6,
        true,
        true,
        '{"experience": 16}'
    ),
    (
        'Toth Orsolya',
        'orsolya.toth@example.com',
        'MGT',
        'PM',
        58591,
        4800,
        4,
        5,
        true,
        true,
        '{"experience": 5}'
    ),
    (
        'Molnar Gabor',
        'gabor.molnar@example.com',
        'OPS',
        'OPS_MGR',
        147998,
        5883,
        3,
        6,
        false,
        true,
        '{"experience": 10}'
    ),
    (
        'Kelemen Andras',
        'andras.kelemen@example.com',
        'MGT',
        'PM',
        91416,
        1711,
        3,
        4,
        true,
        true,
        '{"experience": 5, "certifications": ["AWS", "PMP"]}'
    ),
    (
        'Lakatos Peter',
        'peter.lakatos@example.com',
        'FIN',
        'FIN_ANL',
        64666,
        8753,
        4,
        6,
        true,
        true,
        '{"experience": 4}'
    ),
    (
        'Simon Ferenc',
        'ferenc.simon@example.com',
        'FIN',
        'FIN_ANL',
        77532,
        3562,
        3,
        14,
        true,
        true,
        '{"experience": 12}'
    ),
    (
        'Nagy Laszlo',
        'laszlo.nagy@example.com',
        'ENG',
        'SWE',
        46213,
        8143,
        3,
        12,
        true,
        true,
        '{"experience": 7, "tags": ["docker", "js"]}'
    ),
    (
        'Toth Gabor',
        'gabor.toth@example.com',
        'HR',
        'HR_SPEC',
        49246,
        11422,
        3,
        4,
        true,
        true,
        '{"experience": 8}'
    ),
    (
        'Hegedus Orsolya',
        'orsolya.hegedus@example.com',
        'HR',
        'HR_SPEC',
        132904,
        13396,
        2,
        13,
        true,
        true,
        '{"experience": 1}'
    ),
    (
        'Juhasz Kata',
        'kata.juhasz@example.com',
        'OPS',
        'OPS_MGR',
        52589,
        12196,
        2,
        9,
        true,
        true,
        '{"experience": 13}'
    ),
    (
        'Takacs Cecil',
        'cecil.takacs@example.com',
        'ENG',
        'SWE',
        57806,
        553,
        3,
        12,
        false,
        true,
        '{"experience": 11, "tags": ["vue", "aws", "docker"]}'
    ),
    (
        'Simon Elemer',
        'elemer.simon@example.com',
        'DSG',
        'DSG_UI',
        103657,
        16104,
        5,
        13,
        true,
        true,
        '{"experience": 18}'
    ),
    (
        'Kelemen Peter',
        'peter.kelemen@example.com',
        'MGT',
        'PM',
        71850,
        763,
        4,
        8,
        true,
        true,
        '{"experience": 18}'
    ),
    (
        'Kiss Mari',
        'mari.kiss@example.com',
        'FIN',
        'FIN_ANL',
        86630,
        15426,
        3,
        12,
        true,
        true,
        '{"experience": 17}'
    ),
    (
        'Szabo Ferenc',
        'ferenc.szabo@example.com',
        'SALES',
        'SALES_REP',
        81533,
        19631,
        5,
        15,
        true,
        true,
        '{"experience": 7}'
    ),
    (
        'Nemeth Elemer',
        'elemer.nemeth@example.com',
        'FIN',
        'FIN_ANL',
        109387,
        18934,
        1,
        6,
        true,
        true,
        '{"experience": 14}'
    ),
    (
        'Molnar Kata',
        'kata.molnar@example.com',
        'SALES',
        'SALES_REP',
        65333,
        7330,
        4,
        11,
        true,
        true,
        '{"experience": 15}'
    ),
    (
        'Molnar Cecil',
        'cecil.molnar@example.com',
        'FIN',
        'FIN_ANL',
        121444,
        1993,
        5,
        2,
        true,
        true,
        '{"experience": 3}'
    ),
    (
        'Szabo David',
        'david.szabo@example.com',
        'ENG',
        'SWE',
        68409,
        11738,
        5,
        8,
        true,
        true,
        '{"experience": 20, "tags": ["docker", "vue", "java", "react"]}'
    ),
    (
        'Juhasz Reka',
        'reka.juhasz@example.com',
        'MGT',
        'PM',
        80023,
        19671,
        5,
        6,
        true,
        true,
        '{"experience": 16, "certifications": ["AWS", "CISSP"]}'
    ),
    (
        'Toth Jozsef',
        'jozsef.toth@example.com',
        'FIN',
        'FIN_ANL',
        75973,
        9674,
        4,
        10,
        true,
        true,
        '{"experience": 12}'
    ),
    (
        'Lakatos Ferenc',
        'ferenc.lakatos@example.com',
        'SALES',
        'SALES_REP',
        129584,
        499,
        1,
        2,
        true,
        true,
        '{"experience": 13}'
    ),
    (
        'Varga Luca',
        'luca.varga@example.com',
        'HR',
        'HR_SPEC',
        149473,
        2562,
        5,
        7,
        true,
        true,
        '{"experience": 9}'
    ),
    (
        'Kovacs Elemer',
        'elemer.kovacs@example.com',
        'HR',
        'HR_SPEC',
        61497,
        9556,
        4,
        11,
        true,
        true,
        '{"experience": 8}'
    ),
    (
        'Farkas Gyorgy',
        'gyorgy.farkas@example.com',
        'ENG',
        'SWE',
        114125,
        2011,
        3,
        11,
        true,
        true,
        '{"experience": 10, "tags": ["docker", "aws"]}'
    ),
    (
        'Kiss Sandor',
        'sandor.kiss@example.com',
        'ENG',
        'SWE',
        54619,
        8194,
        3,
        8,
        true,
        true,
        '{"experience": 14, "tags": ["kubernetes", "js", "vue"]}'
    ),
    (
        'Balog Laszlo',
        'laszlo.balog@example.com',
        'ENG',
        'SWE',
        47501,
        11621,
        1,
        5,
        false,
        true,
        '{"experience": 9, "tags": ["vue", "java", "docker", "js"]}'
    ),
    (
        'Varga Laszlo',
        'laszlo.varga@example.com',
        'DSG',
        'DSG_UI',
        86914,
        15029,
        5,
        7,
        true,
        true,
        '{"experience": 15}'
    ),
    (
        'Meszaros Hugo',
        'hugo.meszaros@example.com',
        'DSG',
        'DSG_UI',
        85641,
        9771,
        4,
        4,
        true,
        false,
        '{"experience": 9}'
    ),
    (
        'Papp Luca',
        'luca.papp@example.com',
        'SALES',
        'SALES_REP',
        108761,
        288,
        3,
        8,
        true,
        true,
        '{"experience": 11}'
    ),
    (
        'Kovacs Istvan',
        'istvan.kovacs@example.com',
        'ENG',
        'SWE',
        119410,
        2674,
        4,
        8,
        true,
        true,
        '{"experience": 20, "tags": ["docker", "java", "kubernetes"]}'
    ),
    (
        'Papp Mari',
        'mari.papp@example.com',
        'DSG',
        'DSG_UI',
        111496,
        19775,
        5,
        4,
        true,
        true,
        '{"experience": 12}'
    ),
    (
        'Nagy Luca',
        'luca.nagy@example.com',
        'FIN',
        'FIN_ANL',
        99435,
        10246,
        4,
        13,
        true,
        true,
        '{"experience": 11}'
    ),
    (
        'Kiss Cecil',
        'cecil.kiss@example.com',
        'OPS',
        'OPS_MGR',
        74006,
        10023,
        2,
        13,
        true,
        true,
        '{"experience": 12}'
    ),
    (
        'Meszaros Janos',
        'janos.meszaros@example.com',
        'DSG',
        'DSG_UI',
        77500,
        10229,
        3,
        9,
        true,
        true,
        '{"experience": 10}'
    ),
    (
        'Balog Adam',
        'adam.balog@example.com',
        'MGT',
        'PM',
        53089,
        11994,
        1,
        5,
        false,
        true,
        '{"experience": 11}'
    ),
    (
        'Kiss Andras',
        'andras.kiss@example.com',
        'ENG',
        'SWE',
        97701,
        16637,
        1,
        1,
        true,
        true,
        '{"experience": 12, "tags": ["sql", "aws", "python", "vue"]}'
    ),
    (
        'Nagy Adam',
        'adam.nagy@example.com',
        'FIN',
        'FIN_ANL',
        47779,
        2361,
        2,
        11,
        true,
        true,
        '{"experience": 13}'
    ),
    (
        'Kelemen Mari',
        'mari.kelemen@example.com',
        'OPS',
        'OPS_MGR',
        136398,
        6049,
        2,
        10,
        true,
        true,
        '{"experience": 2}'
    ),
    (
        'Kiss Andras',
        'andras.kiss@example.com',
        'DSG',
        'DSG_UI',
        73694,
        10328,
        5,
        3,
        true,
        true,
        '{"experience": 9}'
    ),
    (
        'Lakatos Istvan',
        'istvan.lakatos@example.com',
        'OPS',
        'OPS_MGR',
        115278,
        10922,
        1,
        3,
        true,
        true,
        '{"experience": 9}'
    ),
    (
        'Takacs Janos',
        'janos.takacs@example.com',
        'HR',
        'HR_SPEC',
        97599,
        1293,
        5,
        2,
        true,
        false,
        '{"experience": 17}'
    ),
    (
        'Meszaros Zsuzsanna',
        'zsuzsanna.meszaros@example.com',
        'DSG',
        'DSG_UI',
        122451,
        5544,
        4,
        7,
        true,
        true,
        '{"experience": 15}'
    ),
    (
        'Juhasz Cecil',
        'cecil.juhasz@example.com',
        'ENG',
        'SWE',
        92266,
        8602,
        3,
        10,
        true,
        true,
        '{"experience": 1, "tags": ["docker"]}'
    ),
    (
        'Kelemen Ferenc',
        'ferenc.kelemen@example.com',
        'FIN',
        'FIN_ANL',
        100368,
        16127,
        2,
        15,
        true,
        true,
        '{"experience": 6}'
    ),
    (
        'Kelemen Janos',
        'janos.kelemen@example.com',
        'MGT',
        'PM',
        69839,
        14305,
        3,
        1,
        false,
        false,
        '{"experience": 10}'
    ),
    (
        'Hegedus Cecil',
        'cecil.hegedus@example.com',
        'MGT',
        'PM',
        86703,
        558,
        5,
        7,
        true,
        true,
        '{"experience": 20, "certifications": ["PMP", "CKA"]}'
    ),
    (
        'Kiss David',
        'david.kiss@example.com',
        'SALES',
        'SALES_REP',
        100299,
        15588,
        4,
        15,
        true,
        true,
        '{"experience": 7}'
    ),
    (
        'Nagy Timea',
        'timea.nagy@example.com',
        'FIN',
        'FIN_ANL',
        58166,
        11410,
        2,
        4,
        true,
        true,
        '{"experience": 14}'
    ),
    (
        'Lakatos Attila',
        'attila.lakatos@example.com',
        'SALES',
        'SALES_REP',
        113747,
        5801,
        3,
        5,
        true,
        false,
        '{"experience": 9}'
    ),
    (
        'Nemeth Luca',
        'luca.nemeth@example.com',
        'DSG',
        'DSG_UI',
        90750,
        15037,
        3,
        10,
        false,
        true,
        '{"experience": 10}'
    ),
    (
        'Simon Peter',
        'peter.simon@example.com',
        'ENG',
        'SWE',
        47813,
        15453,
        5,
        7,
        true,
        true,
        '{"experience": 20, "tags": ["js", "sql"]}'
    ),
    (
        'Kovacs Ferenc',
        'ferenc.kovacs@example.com',
        'FIN',
        'FIN_ANL',
        118302,
        4301,
        1,
        3,
        true,
        true,
        '{"experience": 4}'
    ),
    (
        'Kovacs Attila',
        'attila.kovacs@example.com',
        'FIN',
        'FIN_ANL',
        108882,
        13731,
        3,
        9,
        true,
        true,
        '{"experience": 9}'
    ),
    (
        'Papp Gyorgy',
        'gyorgy.papp@example.com',
        'SALES',
        'SALES_REP',
        146044,
        15687,
        5,
        14,
        true,
        true,
        '{"experience": 19}'
    ),
    (
        'Toth Janos',
        'janos.toth@example.com',
        'SALES',
        'SALES_REP',
        112887,
        6359,
        5,
        10,
        false,
        true,
        '{"experience": 7}'
    ),
    (
        'Lakatos Orsolya',
        'orsolya.lakatos@example.com',
        'OPS',
        'OPS_MGR',
        67249,
        2672,
        4,
        12,
        true,
        true,
        '{"experience": 9}'
    ),
    (
        'Juhasz Sandor',
        'sandor.juhasz@example.com',
        'HR',
        'HR_SPEC',
        105978,
        15022,
        1,
        14,
        true,
        true,
        '{"experience": 7}'
    ) ON CONFLICT (id) DO NOTHING;