-- Datagrid Database Functions (Consolidated Hybrid Mode)
-- High-performance execution wrappers for SQL generated by HTMX/Go.
SET search_path TO datagrid,
    public;
-- 1. Helper: Ensure JSONB is an object
CREATE OR REPLACE FUNCTION datagrid.datagrid_safe_object(j jsonb) RETURNS jsonb LANGUAGE sql IMMUTABLE PARALLEL SAFE RETURN CASE
        WHEN jsonb_typeof(j) = 'object' THEN j
        ELSE '{}'::jsonb
    END;
-- 2. Helper: Convert JSONB object to CSV line
CREATE OR REPLACE FUNCTION datagrid.jsonb_object_to_csv_line(p_json jsonb) RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
SELECT string_agg(
        format('%L', value),
        ','
        ORDER BY key
    )
FROM jsonb_each_text(p_json);
$$;
-- 2. JSON Execution Wrapper
-- Takes raw SQL and JSON data, returns a set of JSON objects for streaming.
DROP FUNCTION IF EXISTS datagrid.datagrid_execute_json(p_sql text, p_data jsonb);
CREATE OR REPLACE FUNCTION datagrid.datagrid_execute_json(p_sql text, p_data jsonb) RETURNS SETOF jsonb AS $$ BEGIN RETURN QUERY EXECUTE format('SELECT to_jsonb(t) FROM (%s) t', p_sql) USING datagrid.datagrid_safe_object(p_data);
END;
$$ LANGUAGE plpgsql;
-- 3. CSV Execution Wrapper
-- Takes raw SQL and JSON data, returns CSV text lines for streaming.
-- Optimized via set-based aggregation and RETURN QUERY for memory efficiency.
DROP FUNCTION IF EXISTS datagrid.datagrid_execute_csv(p_sql text, p_data jsonb);
CREATE OR REPLACE FUNCTION datagrid.datagrid_execute_csv(p_sql text, p_data jsonb) RETURNS SETOF text AS $$
DECLARE v_header text;
v_safe_data jsonb := datagrid.datagrid_safe_object(p_data);
BEGIN -- 3.1 Get & Return Header (Keys ordered by name for consistency with data lines)
EXECUTE format(
    'SELECT string_agg(quote_ident(key), '','' ORDER BY key)
         FROM (SELECT key FROM jsonb_object_keys((SELECT to_jsonb(t) FROM (%s LIMIT 1) t)) key) sub',
    p_sql
) INTO v_header USING v_safe_data;
IF v_header IS NOT NULL THEN RETURN NEXT v_header;
END IF;
-- 3.2 Stream Content (Set-based aggregation per row)
RETURN QUERY EXECUTE format(
    'SELECT datagrid.jsonb_object_to_csv_line(to_jsonb(t)) FROM (%s) AS t',
    p_sql
) USING v_safe_data;
END;
$$ LANGUAGE plpgsql;
DROP FUNCTION IF EXISTS datagrid.datagrid_execute_sql(text, jsonb);